"""
PixelEvent model — stores customer journey events from Shopify Web Pixel.

Captures page views, product views, add-to-cart, checkout events etc.
for multi-touch attribution and funnel analysis.
"""

import uuid

from sqlalchemy import Column, String, DateTime, Index
from sqlalchemy.dialects.postgresql import JSONB

from src.db_base import Base
from src.models.base import TimestampMixin, TenantScopedMixin


class PixelEvent(Base, TimestampMixin, TenantScopedMixin):
    """
    Customer journey event captured by the Shopify Web Pixel.

    Events are sent from the customer's browser via the pixel endpoint.
    No JWT auth — validation is via shop_domain lookup.
    """

    __tablename__ = "pixel_events"

    id = Column(
        String(255),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        comment="Primary key (UUID)",
    )
    shop_domain = Column(
        String(255),
        nullable=False,
        comment="Shopify store domain (used for validation)",
    )
    session_id = Column(
        String(255),
        nullable=False,
        comment="Anonymous browser session ID (generated by pixel)",
    )
    event_type = Column(
        String(100),
        nullable=False,
        comment="Event type: page_viewed, product_viewed, checkout_started, etc.",
    )
    event_data = Column(
        JSONB,
        nullable=True,
        comment="Full event payload (product info, cart contents, etc.)",
    )
    page_url = Column(
        String(2048),
        nullable=True,
        comment="Page URL where the event occurred",
    )
    referrer = Column(
        String(2048),
        nullable=True,
        comment="Referrer URL",
    )

    # UTM attribution fields (captured on landing page)
    utm_source = Column(String(255), nullable=True)
    utm_medium = Column(String(255), nullable=True)
    utm_campaign = Column(String(500), nullable=True)
    utm_term = Column(String(500), nullable=True)
    utm_content = Column(String(500), nullable=True)

    event_timestamp = Column(
        DateTime(timezone=True),
        nullable=False,
        comment="When the event occurred in the browser",
    )

    __table_args__ = (
        Index("ix_pixel_events_tenant_session", "tenant_id", "session_id"),
        Index("ix_pixel_events_tenant_type_ts", "tenant_id", "event_type", "event_timestamp"),
        Index("ix_pixel_events_tenant_ts", "tenant_id", "event_timestamp"),
    )

    def __repr__(self) -> str:
        return (
            f"<PixelEvent(id={self.id}, type={self.event_type}, "
            f"session={self.session_id})>"
        )
