version: 2

# Schema tests for dbt models
# These tests validate data quality and enforce constraints

models:
  # ============================================
  # STAGING MODELS
  # ============================================
  # Note: _tenant_airbyte_connections and all staging models (stg_*)
  # are defined in models/staging/schema.yml

  # ============================================
  # FACT MODELS
  # ============================================
  # Note: fact_orders, fact_ad_spend, and fact_campaign_performance
  # are defined in models/facts/schema.yml
