version: 2

# Schema tests for dbt models
# These tests validate data quality and enforce constraints

models:
  # ============================================
  # STAGING MODELS
  # ============================================
  # Note: _tenant_airbyte_connections and staging models (stg_*)
  # are defined in models/staging/schema.yml

  - name: stg_shopify_orders
    description: "Staging model for Shopify orders"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - not_null
          - unique
      - name: created_at
        description: "Order creation timestamp"
        tests:
          - not_null
      - name: total_price
        description: "Order total price"
        tests:
          - not_null
      - name: currency
        description: "Order currency code"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CNY']
      - name: tenant_id
        description: "Tenant identifier"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('_tenant_airbyte_connections')
                field: tenant_id

  - name: stg_shopify_customers
    description: "Staging model for Shopify customers"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - not_null
          - unique
      - name: email
        description: "Customer email address"
        tests:
          - not_null
      - name: created_at
        description: "Customer creation timestamp"
        tests:
          - not_null
      - name: orders_count
        description: "Number of orders placed"
        tests:
          - not_null
      - name: total_spent
        description: "Total amount spent"
        tests:
          - not_null
      - name: currency
        description: "Currency code"
        tests:
          - not_null
      - name: tenant_id
        description: "Tenant identifier"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('_tenant_airbyte_connections')
                field: tenant_id

  - name: stg_meta_ads
    description: "Staging model for Meta (Facebook) ads data"
    columns:
      - name: ad_account_id
        description: "Meta ad account ID"
        tests:
          - not_null
      - name: campaign_id
        description: "Campaign ID"
        tests:
          - not_null
      - name: date
        description: "Performance date"
        tests:
          - not_null
      - name: spend
        description: "Ad spend amount"
        tests:
          - not_null
      - name: impressions
        description: "Number of impressions"
        tests:
          - not_null
      - name: clicks
        description: "Number of clicks"
        tests:
          - not_null
      - name: conversions
        description: "Number of conversions"
        tests:
          - not_null
      - name: currency
        description: "Currency code"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CNY']
      - name: platform
        description: "Ad platform identifier"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['meta_ads']
      - name: tenant_id
        description: "Tenant identifier"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('_tenant_airbyte_connections')
                field: tenant_id

  - name: stg_google_ads
    description: "Staging model for Google Ads data"
    columns:
      - name: ad_account_id
        description: "Google ad account ID"
        tests:
          - not_null
      - name: campaign_id
        description: "Campaign ID"
        tests:
          - not_null
      - name: date
        description: "Performance date"
        tests:
          - not_null
      - name: spend
        description: "Ad spend amount"
        tests:
          - not_null
      - name: impressions
        description: "Number of impressions"
        tests:
          - not_null
      - name: clicks
        description: "Number of clicks"
        tests:
          - not_null
      - name: conversions
        description: "Number of conversions"
        tests:
          - not_null
      - name: currency
        description: "Currency code"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CNY']
      - name: platform
        description: "Ad platform identifier"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['google_ads']
      - name: tenant_id
        description: "Tenant identifier"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('_tenant_airbyte_connections')
                field: tenant_id

  # ============================================
  # FACT MODELS
  # ============================================
  # Note: fact_orders, fact_ad_spend, and fact_campaign_performance
  # are defined in models/facts/schema.yml
