{#
    Macro: get_approved_columns

    Returns a dictionary of model_name -> [approved_column_names] for all
    governed staging models. This is the compile-time source of truth for
    schema drift detection.

    The canonical reference files are governance/approved_columns_*.yml.
    When updating an allowlist YAML, also update the corresponding entry
    here and open a PR for review.

    Usage:
        {% set all_approved = get_approved_columns() %}
        {% set cols = all_approved.get('stg_shopify_orders', []) %}
#}

{% macro get_approved_columns() %}

  {% set approved = {

    'stg_shopify_orders': [
      'tenant_id',
      'order_id',
      'order_name',
      'order_number',
      'report_date',
      'customer_email',
      'customer_id_raw',
      'created_at',
      'updated_at',
      'cancelled_at',
      'closed_at',
      'total_price',
      'subtotal_price',
      'total_tax',
      'currency',
      'financial_status',
      'fulfillment_status',
      'tags',
      'note',
      'refunds_json',
      'airbyte_record_id',
      'airbyte_emitted_at'
    ],

    'stg_shopify_customers': [
      'customer_id',
      'email',
      'first_name',
      'last_name',
      'full_name',
      'phone',
      'created_at',
      'updated_at',
      'accepts_marketing',
      'verified_email',
      'orders_count',
      'total_spent',
      'currency',
      'state',
      'country_code',
      'city',
      'tags',
      'note',
      'airbyte_record_id',
      'airbyte_emitted_at',
      'tenant_id'
    ],

    'stg_meta_ads': [
      'tenant_id',
      'report_date',
      'date',
      'date_stop',
      'source',
      'ad_account_id',
      'campaign_id',
      'adset_id',
      'ad_id',
      'internal_account_id',
      'internal_campaign_id',
      'platform_channel',
      'canonical_channel',
      'spend',
      'impressions',
      'clicks',
      'conversions',
      'conversion_value',
      'currency',
      'cpm',
      'cpc',
      'ctr',
      'cpa',
      'roas_platform',
      'campaign_name',
      'adset_name',
      'ad_name',
      'objective',
      'reach',
      'frequency',
      'cpp',
      'platform',
      'airbyte_record_id',
      'airbyte_emitted_at'
    ],

    'stg_google_ads': [
      'tenant_id',
      'report_date',
      'date',
      'source',
      'ad_account_id',
      'campaign_id',
      'ad_group_id',
      'ad_id',
      'internal_account_id',
      'internal_campaign_id',
      'platform_channel',
      'canonical_channel',
      'spend',
      'impressions',
      'clicks',
      'conversions',
      'conversion_value',
      'currency',
      'cpm',
      'cpc',
      'ctr',
      'cpa',
      'roas_platform',
      'campaign_name',
      'ad_group_name',
      'ad_type',
      'device',
      'network',
      'average_cpc',
      'cost_per_conversion',
      'platform',
      'airbyte_record_id',
      'airbyte_emitted_at'
    ],

    'stg_tiktok_ads': [
      'tenant_id',
      'report_date',
      'date',
      'source',
      'ad_account_id',
      'campaign_id',
      'adgroup_id',
      'ad_id',
      'internal_account_id',
      'internal_campaign_id',
      'platform_channel',
      'canonical_channel',
      'spend',
      'impressions',
      'clicks',
      'conversions',
      'conversion_value',
      'currency',
      'cpm',
      'cpc',
      'ctr',
      'cpa',
      'roas_platform',
      'campaign_name',
      'adgroup_name',
      'ad_name',
      'objective',
      'reach',
      'frequency',
      'cost_per_conversion',
      'platform',
      'airbyte_record_id',
      'airbyte_emitted_at'
    ],

    'stg_klaviyo_events': [
      'tenant_id',
      'event_id',
      'event_type',
      'event_type_raw',
      'event_timestamp',
      'report_date',
      'source',
      'profile_id_hash',
      'campaign_id',
      'campaign_name',
      'message_id',
      'flow_id',
      'flow_name',
      'flow_message_id',
      'attribution_source',
      'internal_campaign_id',
      'platform_channel',
      'canonical_channel',
      'email_subject',
      'list_name',
      'clicked_url',
      'bounce_type',
      'revenue',
      'currency',
      'order_id',
      'platform',
      'metric_id',
      'airbyte_record_id',
      'airbyte_emitted_at'
    ],

    'stg_klaviyo_campaigns': [
      'tenant_id',
      'campaign_id',
      'campaign_name',
      'report_date',
      'source',
      'internal_campaign_id',
      'platform_channel',
      'canonical_channel',
      'sends',
      'deliveries',
      'opens',
      'unique_opens',
      'clicks',
      'unique_clicks',
      'bounces',
      'spam_complaints',
      'unsubscribes',
      'conversions',
      'unique_recipients',
      'revenue',
      'currency',
      'delivery_rate',
      'open_rate',
      'click_rate',
      'click_to_open_rate',
      'bounce_rate',
      'unsubscribe_rate',
      'spam_rate',
      'conversion_rate',
      'revenue_per_email',
      'platform',
      'airbyte_emitted_at'
    ],

    'stg_shopify_email_events': [
      'tenant_id',
      'activity_id',
      'event_type',
      'event_type_raw',
      'event_timestamp',
      'report_date',
      'source',
      'customer_id_hash',
      'campaign_id',
      'campaign_name',
      'marketing_channel',
      'internal_campaign_id',
      'platform_channel',
      'canonical_channel',
      'email_subject',
      'clicked_url',
      'bounce_type',
      'revenue',
      'currency',
      'order_id',
      'platform',
      'airbyte_record_id',
      'airbyte_emitted_at'
    ]

  } %}

  {{ return(approved) }}

{% endmacro %}
