version: 2

sources:
  - name: airbyte_raw
    description: Raw Airbyte data tables
    database: "{{ target.database }}"
    schema: "{{ target.schema }}"
    
    tables:
      - name: _airbyte_raw_shopify_orders
        description: Raw Shopify orders data from Airbyte
        columns:
          - name: _airbyte_ab_id
            description: Airbyte record ID
          - name: _airbyte_emitted_at
            description: Timestamp when record was emitted by Airbyte
          - name: _airbyte_data
            description: JSONB column containing the actual order data
      
      - name: _airbyte_raw_shopify_customers
        description: Raw Shopify customers data from Airbyte
        columns:
          - name: _airbyte_ab_id
            description: Airbyte record ID
          - name: _airbyte_emitted_at
            description: Timestamp when record was emitted by Airbyte
          - name: _airbyte_data
            description: JSONB column containing the actual customer data

  - name: platform
    description: Platform tables for tenant mapping and configuration
    database: "{{ target.database }}"
    schema: "{{ target.schema }}"
    
    tables:
      - name: tenant_airbyte_connections
        description: Maps Airbyte connections to tenants for data isolation
        columns:
          - name: airbyte_connection_id
            description: Airbyte connection ID
          - name: tenant_id
            description: Tenant identifier
          - name: source_type
            description: Type of data source (e.g., shopify)
          - name: status
            description: Connection status
          - name: is_enabled
            description: Whether connection is enabled
