version: 2

models:
  - name: fact_orders_current
    description: |
      Governed semantic view for Shopify order data.

      This is the ONLY entry point downstream consumers (Superset dashboards,
      AI marts) should use for order data. It hides physical table names,
      version changes, and internal columns.

      Current target: fact_orders v1 (registered 2025-06-01)

      Column contract: 21 approved columns. Excluded columns:
        - platform (deprecated, use source_platform)
        - refunds_json (internal, used by fct_revenue)
        - airbyte_record_id (internal audit)
        - ingested_at (internal audit)

      Tenant isolation: WHERE tenant_id IS NOT NULL enforced in view SQL.
    config:
      tags: ['semantic', 'governed', 'orders']
    tests:
      - test_freshness:
          arguments:
            column_name: dbt_updated_at
            error_after_hours: 48
          config:
            severity: error
    columns:
      - name: id
        description: Surrogate key (MD5 hash of tenant_id + order_id)
        tests:
          - not_null
          - unique
      - name: tenant_id
        description: Tenant identifier for data isolation (mandatory on every row)
        meta:
          superset_expose: true
        tests:
          - not_null
          - relationships:
              to: ref('_tenant_airbyte_connections')
              field: tenant_id
              config:
                where: "tenant_id is not null"
      - name: order_id
        description: Shopify order ID (normalized, without gid:// prefix)
        meta:
          superset_expose: true
        tests:
          - not_null
      - name: order_name
        description: Order name/number from Shopify (e.g., #1001)
        meta:
          superset_expose: true
      - name: order_number
        description: Order number as integer
      - name: customer_key
        description: Pseudonymized customer identifier (MD5 hash, no PII exposed)
        meta:
          superset_expose: true
        tests:
          - not_null
      - name: source_platform
        description: Source platform identifier (canonical)
        meta:
          superset_expose: true
        tests:
          - not_null
          - accepted_values:
              values: ['shopify']
      - name: order_created_at
        description: Order creation timestamp (UTC)
        meta:
          superset_expose: true
        tests:
          - not_null
      - name: order_updated_at
        description: Order last update timestamp (UTC)
      - name: order_cancelled_at
        description: Order cancellation timestamp (UTC, nullable)
      - name: order_closed_at
        description: Order closure timestamp (UTC, nullable)
      - name: date
        description: Order date in tenant's local timezone (canonical per User Story 7.7.1)
        meta:
          superset_expose: true
        tests:
          - not_null
      - name: revenue_gross
        description: Total order revenue including tax
        tests:
          - not_null
      - name: revenue_net
        description: Order subtotal before tax
        tests:
          - not_null
      - name: currency
        description: ISO 4217 currency code
        tests:
          - not_null

  - name: v_marketing_spend
    description: |
      Stable semantic view over canonical marketing spend.

      This view provides a stable interface for downstream consumers. Unifies
      ad spend from Meta, Google, TikTok, and Snapchat into a single view.

      SECURITY: Tenant isolation enforced via tenant_id.
    columns:
      - name: tenant_id
        description: Tenant identifier for data isolation
        tests:
          - not_null
      - name: spend_key
        description: Stable surrogate key for the spend record
        tests:
          - not_null
          - unique
      - name: date
        description: Date of the spend
        tests:
          - not_null
      - name: source_platform
        description: Source platform identifier
        tests:
          - not_null
      - name: channel
        description: Marketing channel (paid_social, paid_search, other)
        tests:
          - not_null
      - name: spend
        description: Amount spent
        tests:
          - not_null
      - name: currency
        description: ISO 4217 currency code
        tests:
          - not_null

  - name: v_campaign_performance
    description: |
      Stable semantic view over canonical campaign performance.

      This view provides a stable interface for downstream consumers. Exposes
      campaign-level performance metrics with calculated rates.

      SECURITY: Tenant isolation enforced via tenant_id.
    columns:
      - name: tenant_id
        description: Tenant identifier for data isolation
        tests:
          - not_null
      - name: campaign_performance_key
        description: Stable surrogate key for the performance record
        tests:
          - not_null
          - unique
      - name: date
        description: Date of the performance metrics
        tests:
          - not_null
      - name: source_platform
        description: Source platform identifier
        tests:
          - not_null
      - name: channel
        description: Marketing channel (paid_social, paid_search, other)
        tests:
          - not_null
      - name: campaign_id
        description: Campaign ID
        tests:
          - not_null
      - name: spend
        description: Amount spent
        tests:
          - not_null
      - name: currency
        description: ISO 4217 currency code
        tests:
          - not_null
