{{
    config(
        materialized='incremental',
        unique_key='id',
        schema='analytics',
        on_schema_change='append_new_columns'
    )
}}

{#
    Customer Sessions model — aggregates pixel events into sessions.

    A session is defined as a sequence of events from the same session_id
    (generated by the web pixel per browser visit). Sessions are bounded
    by a 30-minute inactivity timeout.

    This model enables:
    - Customer journey analysis (page → product → cart → checkout → purchase)
    - Session-based attribution (fallback when UTM not in order note_attributes)
    - Funnel conversion metrics

    SECURITY: Tenant isolation enforced via tenant_id.
#}

with pixel_events as (
    select
        tenant_id,
        session_id,
        event_type,
        event_data,
        page_url,
        utm_source,
        utm_medium,
        utm_campaign,
        utm_term,
        utm_content,
        event_timestamp
    from {{ ref('stg_pixel_events') }}
    {% if is_incremental() %}
    where event_timestamp >= (
        select coalesce(
            max(session_end) - interval '3 days',
            '2020-01-01'::timestamp
        )
        from {{ this }}
    )
    {% endif %}
),

-- Get landing page UTM params (from first event in session)
session_utm as (
    select
        tenant_id,
        session_id,
        utm_source,
        utm_medium,
        utm_campaign,
        utm_term,
        utm_content,
        page_url as landing_page_url,
        row_number() over (
            partition by tenant_id, session_id
            order by event_timestamp asc
        ) as event_rank
    from pixel_events
    where utm_source is not null or page_url is not null
),

first_utm as (
    select
        tenant_id,
        session_id,
        utm_source,
        utm_medium,
        utm_campaign,
        utm_term,
        utm_content,
        landing_page_url
    from session_utm
    where event_rank = 1
),

-- Aggregate events per session
session_aggregates as (
    select
        tenant_id,
        session_id,
        min(event_timestamp) as session_start,
        max(event_timestamp) as session_end,
        extract(epoch from max(event_timestamp) - min(event_timestamp))::int as session_duration_seconds,
        count(*) filter (where event_type = 'page_viewed') as pages_viewed,
        count(*) filter (where event_type = 'product_viewed') as products_viewed,
        count(*) filter (where event_type = 'cart_viewed') > 0 as cart_viewed,
        count(*) filter (where event_type = 'checkout_started') > 0 as checkout_started,
        count(*) filter (where event_type = 'checkout_completed') > 0 as checkout_completed,
        count(*) filter (where event_type = 'payment_info_submitted') > 0 as payment_submitted,
        count(*) filter (where event_type = 'search_submitted') as searches,
        count(*) as total_events
    from pixel_events
    group by tenant_id, session_id
),

-- Extract order_id from checkout_completed events
checkout_orders as (
    select distinct
        tenant_id,
        session_id,
        event_data->>'order_id' as order_id
    from pixel_events
    where event_type = 'checkout_completed'
      and event_data->>'order_id' is not null
)

select
    -- Primary key: deterministic hash of session_id + tenant_id
    md5(concat(sa.session_id, '|', sa.tenant_id)) as id,

    sa.tenant_id,
    sa.session_id,

    -- Landing page and UTM attribution
    fu.landing_page_url,
    fu.utm_source,
    fu.utm_medium,
    fu.utm_campaign,
    fu.utm_term,
    fu.utm_content,

    -- Session metrics
    sa.session_start,
    sa.session_end,
    sa.session_duration_seconds,
    sa.pages_viewed,
    sa.products_viewed,
    sa.searches,
    sa.total_events,

    -- Funnel progression flags
    sa.cart_viewed,
    sa.checkout_started,
    sa.payment_submitted,
    sa.checkout_completed,

    -- Order linkage (for session-based attribution fallback)
    co.order_id,

    -- Audit
    current_timestamp as dbt_updated_at

from session_aggregates sa
left join first_utm fu
    on sa.tenant_id = fu.tenant_id
    and sa.session_id = fu.session_id
left join checkout_orders co
    on sa.tenant_id = co.tenant_id
    and sa.session_id = co.session_id
