resource "render_postgres" "markinsight_db" {
  name = "markinsight-db"

  # Render UI label: basic-256mb (provider plan enum uses underscore)
  plan    = "basic_256mb"
  region  = var.region
  version = "15"

  database_name = var.database_name
  database_user = var.database_user
}

resource "render_web_service" "markinsight_api" {
  name   = "markinsight-api"
  plan   = "starter"
  region = var.region

  health_check_path = "/health"

  runtime_source = {
    docker = {
      repo_url        = "https://github.com/joshrkay/Shopify-analytics-app"
      branch          = "main"
      auto_deploy     = true
      dockerfile_path = "./docker/backend.Dockerfile"
      context         = "."
    }
  }

  env_vars = {
    # Source: static production value from render.yaml
    ENV = { value = "production" }

    # Source: generated by render_postgres.markinsight_db
    DATABASE_URL = {
      value = render_postgres.markinsight_db.connection_info.internal_connection_string
    }

    # Source: var.clerk_frontend_api
    CLERK_FRONTEND_API = { value = var.clerk_frontend_api }

    # Source: var.clerk_secret_key
    CLERK_SECRET_KEY = { value = var.clerk_secret_key }

    # Source: var.clerk_webhook_secret
    CLERK_WEBHOOK_SECRET = { value = var.clerk_webhook_secret }

    # Source: var.vite_clerk_publishable_key
    VITE_CLERK_PUBLISHABLE_KEY = { value = var.vite_clerk_publishable_key }

    # Source: var.cors_origins
    CORS_ORIGINS = { value = var.cors_origins }

    # Source: var.shopify_api_key
    SHOPIFY_API_KEY = { value = var.shopify_api_key }

    # Source: var.shopify_api_secret
    SHOPIFY_API_SECRET = { value = var.shopify_api_secret }

    # Source: var.shopify_billing_return_url
    SHOPIFY_BILLING_RETURN_URL = { value = var.shopify_billing_return_url }

    # Source: var.openrouter_api_key
    OPENROUTER_API_KEY = { value = var.openrouter_api_key }

    # Source: var.encryption_key
    ENCRYPTION_KEY = { value = var.encryption_key }
  }
}

# TODO: Not yet supported by Render provider
# The Render Blueprint workflow can model repo-level blueprint orchestration.
# A first-class Terraform "render_blueprint" resource is not currently available.
# resource "render_blueprint" "markinsight" {
#   name = "markinsight"
# }

# TODO: Not yet supported by Render provider
# render.yaml passes VITE_CLERK_PUBLISHABLE_KEY as a Docker build-time value.
# Current Terraform resource models runtime env vars only.
