version: 2

models:
  - name: dim_ad_accounts
    description: |
      Dimension table for ad accounts across all advertising platforms.
      Provides a unified view with:
      - internal_account_id: Deterministic hash for cross-platform joins
      - platform_account_id: Original platform ID
      - source: Platform identifier
    columns:
      - name: internal_account_id
        description: Deterministic internal account ID (MD5 hash)
        tests:
          - not_null
          - unique
      - name: tenant_id
        description: Tenant identifier for data isolation
        tests:
          - not_null
      - name: source
        description: Data source platform
        tests:
          - not_null
          - accepted_values:
              values: ['meta_ads', 'google_ads', 'tiktok_ads', 'pinterest_ads', 'snap_ads', 'amazon_ads']
      - name: platform_account_id
        description: Original platform account ID
        tests:
          - not_null
      - name: currency
        description: Account currency
      - name: first_seen_at
        description: First observation timestamp
      - name: last_seen_at
        description: Most recent observation timestamp

  - name: dim_campaigns
    description: |
      Dimension table for campaigns across all advertising platforms.
      Provides a unified view with:
      - internal_campaign_id: Deterministic hash for cross-platform joins
      - platform_campaign_id: Original platform ID
      - internal_account_id: Links to dim_ad_accounts
    columns:
      - name: internal_campaign_id
        description: Deterministic internal campaign ID (MD5 hash)
        tests:
          - not_null
          - unique
      - name: internal_account_id
        description: Internal account ID (foreign key)
        tests:
          - not_null
          - relationships:
              to: ref('dim_ad_accounts')
              field: internal_account_id
              config:
                severity: warn
      - name: tenant_id
        description: Tenant identifier
        tests:
          - not_null
      - name: source
        description: Data source platform
        tests:
          - not_null
          - accepted_values:
              values: ['meta_ads', 'google_ads', 'tiktok_ads', 'pinterest_ads', 'snap_ads', 'amazon_ads']
      - name: platform_account_id
        description: Original platform account ID
        tests:
          - not_null
      - name: platform_campaign_id
        description: Original platform campaign ID
        tests:
          - not_null
      - name: campaign_name
        description: Campaign name
      - name: campaign_objective
        description: Campaign objective/goal
      - name: campaign_type
        description: Campaign type (network, format)
      - name: currency
        description: Campaign currency
      - name: first_seen_at
        description: First observation timestamp
      - name: last_seen_at
        description: Most recent observation timestamp
